server:
  servlet:
    context-path: /api
spring:
  profiles:
    active: @activatedProperties@
  application:
    name: base
  jackson:
#    default-property-inclusion: non_null
    time-zone: GMT+8
feign:
  client:
    config:
      default:
        connectTimeout: 150000
        readTimeout: 150000
  hystrix:
    enabled: false

#info:
#  name: base
#  server:
#    port: ${server.port}